### PR TITLE
[sdk] Support time synchronization using SNTP

### LINKED ISSUE #3: [Bug] GetClock_RealTime is incorrect
### Reproduction steps

In PR #2 , GetEpochTS has been fully commented out, as GetClock_RealTime will return CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE, causing failure.

### Expected Outcome

GetClock_RealTime to obtain correct timing

### Actual Outcome

 GetClock_RealTime returns CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE instead of actual timing.

### Github SDK version

main

### Integrated Circuit (IC)

_No response_

### Other Inputs

_No response_

### PR DESCRIPTION
**Pull request by SirRu24**
+ Added API to start time and to get time using SNTP at matter_timer module
+ Added API to check if RTC is synced with SNTP
* Updated makefile and zap to build time synchronization feature
* Updated matter RTC APIs
* Sync RTC with SNTP when successfully get time from SNTP
* connectedhomeip update implementation can be seen at https://github.com/pankore/connectedhomeip/commit/d0823095b5f6325512af3b61c084362aaac243d3 and https://github.com/pankore/connectedhomeip/commit/887017c793c5d1d5930789402128f74dd749ea28
* Fix #3

### CODE REVIEW

File: common/port/matter_timers.c [hunk 1]
```diff
@@ -238,6 +239,51 @@ void matter_timer_init(void)
...
+        time_t tick_diff_sec, tick_diff_ms;
+        unsigned int current_tick = xTaskGetTickCount();
+
+        tick_diff_sec = (current_tick - update_tick) / configTICK_RATE_HZ;
+        tick_diff_ms = (current_tick - update_tick) % configTICK_RATE_HZ / portTICK_RATE_MS;
+        update_sec += tick_diff_sec;
+        update_usec += (tick_diff_ms * 1000);
+        *current_sec = update_sec + update_usec / 1000000;
+        *current_usec = update_usec % 1000000;
+        setPref_new(NULL,  secKey,  current_sec, sizeof(time_t));
```
Comment (xshuqun) [inline common/port/matter_timers.c:267]: Why is it necessary to be stored into DCT?

Comment (SirRu24) [reply common/port/matter_timers.c]: Removed the DCT usage in the latest commit. Instead it will read directly from the RTC which is already set by the InitClock_RealTime in the initialization.

**Review by xshuqun — APPROVED** [review]
LGTM
